---
- name: OS basic settings
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: apt upgrade
      apt:
        upgrade: yes
        update_cache: yes

    - name: install packages
      apt:
        pkg:
          - language-pack-ja-base
          - language-pack-ja
          - zip
          - git

    - name: set locale ja_JP.UTF-8
      command: 'localectl set-locale LANG=ja_JP.UTF-8'

    - name: set timezone Asia/Tokyo
      command: 'timedatectl set-timezone Asia/Tokyo'

- name: install AWS CLI
  hosts: all
  become: true
  gather_facts: false

  vars:
    awscli_package_url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
    awscli_work_dir: /tmp/awscil_work

  tasks:
    - name: create awscli work directory
      file:
        path: '{{awscli_work_dir}}'
        state: directory

    - name: download package
      get_url:
        url: '{{ awscli_package_url }}'
        dest: '{{ awscli_work_dir }}/awscliv2.zip'

    - name: extract zip file
      command:
        cmd: 'unzip awscliv2.zip'
        chdir: '{{ awscli_work_dir }}'

    - name: install aws cli
      command:
        cmd: './aws/install'
        chdir: '{{ awscli_work_dir }}'
