---
- name: OS basic settings
  hosts: all
  become: true
  gather_facts: false

  vars:
    user: minecraft
    home_dir: /opt/minecraft

  tasks:
    - name: apt upgrade
      apt:
        upgrade: yes
        update_cache: yes

    - name: install packages
      apt:
        pkg:
          - language-pack-ja-base
          - language-pack-ja
          - zip
          - git

    - name: set locale ja_JP.UTF-8
      command: 'localectl set-locale LANG=ja_JP.UTF-8'

    - name: set timezone Asia/Tokyo
      command: 'timedatectl set-timezone Asia/Tokyo'

    - name: create user
      user:
        name: '{{ user }}'
        home: '{{ home_dir }}'
        create_home: true

- name: install AWS CLI
  hosts: all
  become: true
  gather_facts: false

  vars:
    awscli_package_url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
    awscli_work_dir: /tmp/awscil_work

  tasks:
    - name: create awscli work directory
      file:
        path: '{{awscli_work_dir}}'
        state: directory

    - name: download package
      get_url:
        url: '{{ awscli_package_url }}'
        dest: '{{ awscli_work_dir }}/awscliv2.zip'

    - name: extract zip file
      unarchive:
        src: '{{ awscli_work_dir }}/awscliv2.zip'
        dest: '{{ awscli_work_dir }}'
        remote_src: true

    - name: install aws cli
      command:
        cmd: './aws/install'
        chdir: '{{ awscli_work_dir }}'

- name: install minecraft server
  hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: mc_server_soft_url
      prompt: enter the minecraft server download URL
      private: false

  tasks:
    - name: download minecraft server
      get_url:
        url: '{{ mc_server_soft_url }}'
        dest: /tmp/bedrock-server.zip

    - name: create minecraft server install directory
      file:
        path: /opt/minecraft/bedrock-server
        state: directory
        owner: minecraft
        group: minecraft

    - name: extract zip file
      unarchive:
        src: /tmp/bedrock-server.zip
        dest: /opt/minecraft/bedrock-server
        owner: minecraft
        group: minecraft
        remote_src: true

    - name: put systemd unit file
      copy:
        src: files/systemd/minecraft.service
        dest: /etc/systemd/system/minecraft.service
        owner: root

    - name: put .screenrc
      copy:
        src: files/.screenrc
        dest: /opt/minecraft
        owner: minecraft
        group: minecraft
